#!/bin/bash -l

#SBATCH -q regular
#SBATCH -N 1
#SBATCH --ntasks-per-node=16
#SBATCH -c 8
#SBATCH -t 24:00:00
#SBATCH -J gemx_gpu
#SBATCH -C gpu
#SBATCH --gres=gpu:4
#SBATCH -e run.err
#SBATCH -o run.out
#SBATCH --gpu-bind=map_gpu:0,1,2,3
#SBATCH -A mp118_g

export OMP_PROC_BIND=spread
export OMP_PLACES=threads
export OMP_NUM_THREADS=8

source env.sh
export SLURM_CPU_BIND="cores"
srun ./gemx
