#!/bin/bash
#SBATCH -A mp118
#SBATCH -C cpu
#SBATCH -N 1
#SBATCH -c 1
#SBATCH --qos=regular
#SBATCH --time=12:00:00
#SBATCH --ntasks-per-node=16
#SBATCH -J gemx_cpu

export OMP_PROC_BIND=spread
export OMP_PLACES=threads
export OMP_NUM_THREADS=1

source env.sh
export SLURM_CPU_BIND="cores"
srun -n 16 ./gemx >& run.out