#!/bin/bash -l

#SBATCH -q debug
#SBATCH -N 1
#SBATCH --ntasks-per-node=16
#SBATCH -c 8
#SBATCH -t 00:30:00
#SBATCH -J gemx_gpu_dbg
#SBATCH -C gpu
#SBATCH --gres=gpu:4
#SBATCH -e run.err
#SBATCH -o run.out
#SBATCH --gpu-bind=map_gpu:0,1,2,3
#SBATCH -A mp118_g

export OMP_PROC_BIND=spread
export OMP_PLACES=threads
export OMP_NUM_THREADS=8

#For outputting debug cores.
export ATP_ENABLED=1
ulimit -c unlimited

export SLURM_CPU_BIND="cores"
srun ./gemx